name: Update pkg.go.dev Proxy
on:
  release:
    types:
      - created
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "**/v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Renew documentation
    runs-on: ubuntu-latest
    steps:
      - name: Go proxy warming
        uses: andrewslotin/go-proxy-pull-action@v1.0.2
